class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'm'
        self.UnzipMirrorCommand = 'unm'
        self.TarMirrorCommand = 'tarm'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'cari'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'auth'
        self.UnAuthorizeCommand = 'unauth'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'specs'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speed'
        self.CloneCommand = 'c'
        self.CountCommand = 'count'
        self.WatchCommand = 'w'
        self.TarWatchCommand = 'tarw'
        self.DeleteCommand = 'del'
        self.UsageCommand = 'life'
        self.MediaInfoCommand = 'vinfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'term'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'
        self.InfolainCommand = 'linksupport'

BotCommands = _BotCommands()
